# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r win-x64'
    zipAfterPublish: false

- task: HCLAppScan@1
  inputs:
    AppSecTestService: 'ASOC Creds'
    applications: 'da95c1b0-b179-44e9-a7a2-feca877423bb'
    scanname: 'Automated Scan from Azure DevOps'
    scantype: 'static'
    ScanSpeedOptions: 'thorough'