# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - restore_cache:
          keys:
            - v1-app
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          key: v1-app
          paths:
            - C:\Users\circleci\.nuget\packages
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win-x64

     


