# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - run:
          name: "Test"
          command: |
           $PSVersionTable
           $env:path
           choco install powershell-core -y



          shell: powershell.exe
      - run:
          name: "test PS ver"
          command: |
             $PSVersionTable
          shell: pwsh.exe



